---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuki.
--- DateTime: 2020/8/24 0:05
---

local M = {}

--查找hp高于或者低于value的棋子
---@param combatId number
---@param playerId number
---@param greater boolean
---@param value number
function M.getPawnByHpThan(combatId, playerId, value, greater)
    local player = nn.get_combat(combatId):getPlayer(playerId)
    for i = 0, player:getMaxCombatPawnNumber() do
        local pawn = player:getCombatPawnByIndex(i)
        if pawn then
            if greater then
                if pawn:hp() > value then
                    return pawn
                end
            else
                if pawn:hp() < value then
                    return pawn
                end
            end
        end
    end
end

---@param combatId number
---@param playerId number
---@param greater boolean
---@param value number
function M.getPawnByHpThanAndEqual(combatId, playerId, value, greater)
    local player = nn.get_combat(combatId):getPlayer(playerId)
    for i = 0, player:getMaxCombatPawnNumber() do
        local pawn = player:getCombatPawnByIndex(i)
        if pawn then
            if greater then
                if pawn:hp() >= value then
                    return pawn
                end
            else
                if pawn:hp() <= value then
                    return pawn
                end
            end
        end
    end
end

---@param combatId number
---@param playerId number
---@param value number
function M.getPawnByHpEqual(combatId, playerId, value)
    local player = nn.get_combat(combatId):getPlayer(playerId)
    for i = 0, player:getMaxCombatPawnNumber() do
        local pawn = player:getCombatPawnByIndex(i)
        if pawn then
            if pawn:hp() == value then
                return pawn
            end
        end
    end
end

---@param combatId number
---@param playerId number
---@param max boolean
function M.getPawnByHpMaxOrMin(combatId, playerId, max)
    local player = nn.get_combat(combatId):getPlayer(playerId)
    local target
    for i = 0, player:getMaxCombatPawnNumber() do
        local pawn = player:getCombatPawnByIndex(i)
        if pawn then
            if not target then
                target = pawn
            end
            if max then
                if target:hp() < pawn:hp() then
                    target = pawn
                end
            else
                if target:hp() > pawn:hp() then
                    target = pawn
                end
            end
        end
    end
    return target
end

---获取到一个本回合还没有发动攻击的棋子
---@param combatId number
---@param playerId number
---@return number[]
function M.getPawnNotAttack(combatId, playerId)
    
end

---获取到一个本回合还没有发动攻击的棋子
---@param combatId number
---@param playerId number
---@param pawnUid number
---@return number[]
function M.pawnCanUseSkill(combatId, playerId, pawnUid)
    
end

return M