---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuki.
--- DateTime: 2020/5/11 16:14
---

---这里存放一些lua端的初始化操作
local m = {}

local function init()
    CS.Lib.Listener.Instance:On("scene_changed", function (name)
        require(string.format("modules.%s.init", CS.Global.Scene.name)).init()
    end)
    CS.Lib.Listener.Instance:On("after_app_init", function (name)
        require(string.format("modules.%s.init", name)).init()
    end)
end

m.init = init

return m