---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuki.
--- DateTime: 2020/5/11 16:14
---

---这里存放一些lua端的初始化操作
local m = {}

local function init()
    ---这里就是两个场景跳转相关的事件
    CS.Lib.Listener.Instance:On("scene_changed", function (name)
        local scene = require(string.format("modules.%s.init", CS.Global.Scene.name))
        if scene and scene.init then
            scene.init()
        end
    end)
    
    CS.Lib.Listener.Instance:On("after_app_init", function (name)
        local scene = require(string.format("modules.%s.init", CS.Global.Scene.name))
        if scene and scene.init then
            scene.init()
        end
    end)
end

m.init = init

return m