// Generated by https://quicktype.io

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Entity.Net
{
    public partial class Msg
    {
        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("msg")]
        public string MsgMsg { get; set; }
    }

    public partial class Msg
    {
        public static Msg FromJson(string json) => JsonConvert.DeserializeObject<Msg>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Msg self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}