---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuki.
--- DateTime: 2020/5/12 17:03
---

local M = {}

--- 开始战斗
---@param user table 玩家对象
---@param cards table 当前玩家选择的卡组
function M:Start(user, cards)
    
end

--- 结束战斗，判定战斗结束的时候自动调用(或者通过core部分来调用)
function M:End()
    
end

return M