---@field id number
---@field name string
---@field name_cn string
---@field icon string
---@field img string
---@field hp number
---@field mp number
---@field atk number
---@field mp number
---@field type number
---@field skill1 number
---@field skill2 number
---@field skill3 number
---@field skill4 number
---@field skill5 number
---@class DisplayPawn
local DisplayPawn = {}

---@field id number
---@field name string
---@field name_cn string
---@field cost number
---@field costType number
---@field damage number
---@field damageType number
---@field passive number
---@field disperse number
---@field buff1 number
---@field buff2 number
---@field buff3 number
---@field buff4 number
---@field buff5 number
---@class DisplaySkill
local DisplaySkill = {}

---@field normalDrawPrice number
---@field highDrawPrice number
---@field normal_nPercent number
---@field normal_rPercent number
---@field normal_srPercent number
---@field normal_ssrPercent number
---@field high_nPercent number
---@field high_rPercent number
---@field high_srPercent number
---@field high_ssrPercent number
---@field primaryGold number
---@field salary number
---@field roundCard number
---@field primaryCard number
---@field maxRound number
---@field primaryEnergy number
---@field energyGrow number
---@field maxEnergy number
---@field maxHp number
---@field primaryHp number
---@class GlobalConfig
local GlobalConfig = {}