---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuki.
--- DateTime: 2020/7/12 19:54
---

---@class cpp.Pawn
local Pawn = {}

---@class cpp.Player
local Player = {}

---@class cpp.Buff
local Buff = {}

---@class cpp.BuffMachine
local BuffMachine = {}