---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jauok.
--- DateTime: 2020/6/28 11:18
---

---这个是战斗场景中所需要的各种数据的存储
---@class CombatData
local _m = {}

---当前玩家的卡牌数据(是这个的数组)
---@class combat.OriginCombatCardData
local OriginCombatCardData = {
    id = 1,
    num = 5
}

---运行期，玩家的卡组中所有卡牌的信息
---@class combat.RuntimeCardData
local RuntimeCardData = {
    uid = 1,
    id = 1
}

---运行期玩家卡池中卡牌的信息
---由于每次从卡池中取出数据都是随机取的，而不是顺序的，所以这里是根据卡牌的类型到卡牌信息的映射
---@class combat.RuntimeDeckData
local RuntimeDeckData = {
    ---根据卡牌的类型来分类，存放所有在卡池中的卡牌uid
    {1, 2, 3, 4},
    {},
    {},
    {},
}

---玩家当前手牌中的卡牌信息
---存放的是卡牌的uid
---@class combat.RuntimeHandData
local RuntimeHandData = {
    1, 2, 3, 4
}

---玩家自己的棋盘中的卡牌信息
local myPanel = {0, 0, 0, 0, 0, 0, 0, 0}
---敌方的棋盘中的卡牌信息
local enemyPanel = {0, 0, 0, 0, 0, 0, 0, 0}

---这里的信息将被隐藏，只暴露出一些函数来操作这个
---当前整个战场中所有卡牌的信息
---@class combat.RuntimePanel
local RuntimePanelData = {}

return _m